# Generated by Django 5.0 on 2024-01-05 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('airline_logoText', models.TextField()),
                ('model', models.CharField(max_length=200, null=True)),
                ('seat_numbers', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('hotel_viewText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='default', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paystack_ref', models.CharField(blank=True, max_length=15)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure', models.DateTimeField(default=None)),
                ('arrival', models.DateTimeField(default=None)),
                ('departure_2', models.DateTimeField(blank=True, default=None, null=True)),
                ('arrival_2', models.DateTimeField(blank=True, default=None, null=True)),
                ('passenger', models.CharField(default=1)),
                ('stops', models.PositiveIntegerField(default=1)),
                ('each_extra_luggage_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.airline')),
                ('flight_class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.flight_class')),
                ('depart_from', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booking_depart_from', to='booking.location')),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booking_destination', to='booking.location')),
                ('offer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.offer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trip_round')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('check_in_out', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking_check', to='booking.checkinout')),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking_city', to='booking.city')),
                ('condition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking_condition', to='booking.conditions')),
                ('hotel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking', to='booking.hotel')),
                ('no_of_rooms', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking_room', to='booking.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='HotelCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=250)),
                ('last_name', models.CharField(default=None, max_length=250)),
                ('middle_name', models.CharField(default=None, max_length=250)),
                ('date_of_birth', models.DateField(default=None)),
                ('contact', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.gender')),
                ('hotel_booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.hotelbooking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_checkout_nationality', to='booking.nations')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=250)),
                ('last_name', models.CharField(default=None, max_length=250)),
                ('middle_name', models.CharField(default=None, max_length=250)),
                ('date_of_birth', models.DateField(default=None)),
                ('passport_no', models.CharField(default=None)),
                ('passport_expiry_date', models.DateField(default=None)),
                ('contact', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('seat_no', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_luggage_quantity', models.CharField(default=0)),
                ('extra_luggage_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.gender')),
                ('nationality', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_nationality', to='booking.nations')),
                ('passport_issuing_authority', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_passport_issuing_authority', to='booking.nations')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.checkout')),
                ('flight_status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.flight_status')),
            ],
        ),
    ]
