# Generated by Django 5.0 on 2024-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_hotelbooking_check_in_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='check_out',
        ),
        migrations.AddField(
            model_name='hotelcheckout',
            name='check_in',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hotelcheckout',
            name='check_out',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
